version: '3.9'

services:
    api-kiosk:
        image: node:18-alpine
        container_name: api-kiosk
        build: .
        command: sh ./entrypoint.sh
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 3001:3001
        env_file:
            - ./.env
        environment:
            - MONGO_PATH=kiosk.c32e0lo.mongodb.net
            - PORT=3001
