name: CI

on:
    pull_request:
        branches: '**'

jobs:
    build:
        runs-on: ${{matrix.os}}

        strategy:
            matrix:
                node-version: [18.x]
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: install dependencies
              run: yarn install --frozen-lockfile

            - name: test prettier
              run: yarn prettier:ci

            - name: unit tests
              run: yarn test:unit

            - name: coverage tests
              env:
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  MONGO_PATH: ${{ secrets.MONGO_PATH }}
                  MONGO_USER: ${{ secrets.MONGO_USER }}
                  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
              run: yarn test:coverage

            - name: build
              run: yarn build
